### ISSUE TITLE
Jupyter notebook is dead on running Mine KG triplets from relevant/domain-specific pages

### ISSUE THREAD

**Issue by HariprasadManimozhi** [chaitjo/knowledge-graphs#1]
Jupyter notebook is dead on running "Mine KG triplets from relevant/domain-specific pages".
Can you let know why it is?

**Comment by chaitjo** [comment]
Hi @HariprasadManimozhi, thanks for your interest. Have you installed the dependencies correctly? In particular, it seems the wikipedia API may have an issue for you.

**Comment by HariprasadManimozhi** [comment]
Ok will check..thanks

**Comment by HariprasadManimozhi** [comment]
Closing this issue, since long.
